config/routes.rb
GBlog::Application.routes.draw do

  
  resources :blogs
  
  resources :blog_types

  resources :comments
  
  resources :tools do 
    collection do 
      get "new_blog"
      post "create_blog"
      get "list_blogs"
      get "edit_blog"
      put "update_blog"
      get "delete_blog"
      get "new_blog_type"
      post "create_blog_type"
      get "list_blog_types"
      get "edit_blog_type"
      put "update_blog_type"
      get "delete_blog_type"
      get "list_comments"
      get "delete_comment"
      get "list_visitors"
      get "update_ip_location"
    end
  end
  
  resources :admins do
    collection do 
      get "admin_show"
      get "admin_edit"
      put "admin_update"
    end
  end
  
  resources :statuses

  root :to => "blogs#home"

end

app/controllers/tools_controller.rb
# -*- encoding: utf-8 -*-

class ToolsController < ApplicationController

  before_filter :auth
  
  layout "tools"
  
  def index
    @statuses = [Status.all.count, Status.where("created_at > ?", Time.now.beginning_of_day).count]
    @blogs = [Blog.all.count, Blog.where("created_at > ?", Time.now.beginning_of_day).count]
    @blog_types = [BlogType.all.count, BlogType.where("created_at > ?", Time.now.beginning_of_day).count]
    @comments = [Comment.all.count, Comment.where("created_at > ?", Time.now.beginning_of_day).count]
    @visitors = [Visitor.all.count, Visitor.where("last_access > ?", Time.now.beginning_of_day).count]
  end
  
  def new_blog
    @blog = Blog.new
  end
  
  def create_blog
    # 1. get image and blog content
    img = params[:blog][:image]
    mus = params[:blog][:music]
    att = params[:blog][:attach]
    params[:blog].delete(:image)
    params[:blog].delete(:music)
    params[:blog].delete(:attach)
    # 2. save blog no matter image or submit
    @blog = Blog.create!(params[:blog])
    
    if params[:commit] == "upload"
      # 3. when upload save image if thereis
      if img
        @image = Image.create!(:img => img, :blog_id => @blog.id)
      end
      if mus
        @music = Music.create!(:sound => mus, :blog_id => @blog.id)
      end
      if att
        @attach = Attachment.create!(:file => att, :blog_id => @blog.id)
      end
      
      redirect_to edit_blog_tools_path(:blog_id => @blog.id)
    else
      # 4. or ignore image
      redirect_to blog_path(@blog)
    end
  end
  
  def list_blogs
    page = params[:page] || 1
    @blogs = Blog.order("created_at desc").paginate(:page => page, :per_page => 20)
  end
  
  def edit_blog
    @blog = Blog.find_by_id(params[:blog_id])
    unless @blog
      render :text => "未知blog_id"
    end
  end
  
  def update_blog
    # 1. get image and blog
    img = params[:blog][:image]
    mus = params[:blog][:music]
    params[:blog].delete(:image)
    params[:blog].delete(:music)
    # 2. save blog no matter image or submit 
    @blog = Blog.find_by_id(params[:blog_id])
    if @blog
      @blog.update_attributes!(params[:blog])
    else
      render :text => "未知blog_id"
    end
    
    if params[:commit] == "upload"
      # 3. when upload save image if there is
      if img
        @image = Image.create!(:img => img, :blog_id => @blog.id)
      end
      if mus
        @music = Music.create!(:sound => mus, :blog_id => @blog.id)
      end
      
      redirect_to edit_blog_tools_path(:blog_id => @blog.id)
    else 
      # 4. or ignore image and submit
      redirect_to blog_path(@blog)
    end
  end

  def delete_blog
    @blog = Blog.find_by_id(params[:blog_id])
    if @blog
      @blog.destroy
      redirect_to list_blogs_tools_path
    else 
      render :text => "未知blog_id"
    end
  end
  
  def new_blog_type
    @blog_type = BlogType.new
  end
  
  def create_blog_type
    @blog_type = BlogType.create!(params[:blog_type])
    
    redirect_to blogs_path(:blog_type_id => @blog_type.id)
  end
  
  def list_blog_types
    page = params[:page] || 1
    @blog_types = BlogType.paginate(:page => page, :per_page => 20)
    @default_blogs = Blog.where(:blog_type_id => 0)
  end
  
  def edit_blog_type
    @blog_type = BlogType.find_by_id(params[:blog_type_id])
    unless @blog_type
      render :text => "未知blog_type_id"
    end
  end
  
  def update_blog_type
    @blog_type = BlogType.find_by_id(params[:blog_type_id])
    if @blog_type
      @blog_type.update_attributes!(params[:blog_type])
      redirect_to blog_types_path
    else
      render :text => "未知blog_type_id"
    end
  end

  def delete_blog_type
    @blog_type = BlogType.find_by_id(params[:blog_type_id])
    if @blog_type
      Blog.where(:blog_type_id => @blog_type.id).each do |blog|
        blog.update_attributes!(:blog_type_id => 0)
      end
      @blog_type.destroy
      redirect_to list_blog_types_tools_path
    else
      render :text => "未知blog_type_id"
    end
  end

  def list_comments
    page = params[:page] || 1
    @comments = Comment.order("updated_at desc").paginate(:page => page, :per_page => 20)
  end
  
  def delete_comment
    @comment = Comment.find_by_id(params[:comment_id])
    if @comment
      @comment.destroy
      redirect_to list_comments_tools_path
    else
      render :text => "未知comment_id"
    end
  end

  def list_visitors
    page = params[:page] || 1
    @visitors = Visitor.order("last_access desc").paginate(:page => page, :per_page => 20)
  end

  def update_ip_location
    @visitors = Visitor.where("location is NULL")
    @visitors.each do |visitor|
      visitor.find_location
    end
    redirect_to list_visitors_tools_path
  end

end

app/helpers/tools_helper.rb
# -*- encoding: utf-8 -*-

module ToolsHelper
  
  def admin_funcs
    [["修改头像", admin_edit_admins_path(:type => "avatar")], 
    ["修改照片", admin_edit_admins_path(:type => "photo")], 
    ["修改简介", admin_edit_admins_path(:type => "desc")], 
    ["修改其他信息", admin_edit_admins_path(:type => "info")]]
  end
  
end

app/views/tools/edit_blog.html.haml
.head1 修改博客
#edit_blog
	#blog_images
		- @blog.images.each do |image|
			.image
				= image_link image.img.url, "#", {}, {:image_id => image.id}
				%br
				= "image_id: #{image.id}"
	#blog_musics
		- @blog.musics.each do |music|
			.music
				= link_to "#{music.id}: #{music.sound_file_name}", "#", :music_id => music.id
	#blog_attachs
		- @blog.attachments.each do |attach|
			.attach
				= link_to "#{attach.id}: #{attach.file_file_name}", "#", :attach_id => attach.id
	.trans_add= link_to "添加链接", "#", :id => "link_add"
	.trans_add= link_to "添加代码", "#", :id => "code_add"
	= form_for @blog, :url => update_blog_tools_path(:blog_id => @blog.id), :html => {:multipart => true} do |f|
		.image_upload
			上传图片
			= f.file_field :image
		.music_upload
			上传音乐
			= f.file_field :music
		.attachment_upload
			上传附件
			= f.file_field :attach
		= f.submit "upload"
		= f.text_field :title, :class => "title_input"
		= f.text_area :text, :class => "text_input"
		= f.select :blog_type_id, types_option
		= f.submit "修改", :class => "confirm_button"
		

app/views/tools/edit_blog_type.html.haml
.head1 新建分类
#edit_blog_type
	= form_for @blog_type, :url => update_blog_type_tools_path(:blog_type_id => @blog_type.id) do |f|
		= f.text_field :name, :class => "title_input"
		= f.text_area :desc, :class => "text_input"
		= f.submit "修改", :class => "confirm_button"
		

app/views/tools/index.html.haml
#tools_page
	.head1 后台工具
	#return= link_to "<< 正常模式", root_path
	#admin_function
		- admin_funcs.each do |func|
			.func_item= link_to func[0], func[1]
	#stat_show
		.current_stat
			%div.stat_name Statuses
			%div= @statuses[0]
			%div= @statuses[1]
			%div= link_to "查看", statuses_path
			%div= link_to "编辑", new_status_path
		.current_stat
			%div.stat_name Blogs
			%div= @blogs[0]
			%div= @blogs[1]
			%div= link_to "查看", list_blogs_tools_path
			%div= link_to "新建", new_blog_tools_path
		.current_stat
			%div.stat_name BlogTypes
			%div= @blog_types[0]
			%div= @blog_types[1]
			%div= link_to "查看", list_blog_types_tools_path
			%div= link_to "新建", new_blog_type_tools_path
		.current_stat
			%div.stat_name Comments
			%div= @comments[0]
			%div= @comments[1]
			%div= link_to "查看", list_comments_tools_path
		.current_stat
			%div.stat_name Visitors
			%div= @visitors[0]
			%div= @visitors[1]
			%div= link_to "查看", list_visitors_tools_path

app/views/tools/list_blog_types.html.haml
%table#list_blog_types
	.head1 分类列表
	%tr
		%td 分类名称
		%td 创建日期
		%td 文章数
		%td 操作
	%tr
		%td= link_to "默认分类", blogs_path(:blog_type_id => 0)
		%td ----
		%td= @default_blogs.count
		
	- @blog_types.each do |type|
		%tr
			%td= link_to type.name, blogs_path(:blog_type_id => type.id)
			%td= type.created_at.to_date
			%td= type.blogs_count
			%td
				= link_to "修改", edit_blog_type_tools_path(:blog_type_id => type.id)
				= link_to "删除", delete_blog_type_tools_path(:blog_type_id => type.id)
.pagination= will_paginate @blog_types

app/views/tools/list_blogs.html.haml
%table#list_blogs
	.head1 博客列表
	%tr
		%td 博客名称
		%td 分类
		%td 创建日期
		%td 操作
	- @blogs.each do |blog|
		%tr
			%td= link_to blog.title, blog
			%td= blog.type_name
			%td= blog.created_at.to_date
			%td
				= link_to "修改", edit_blog_tools_path(:blog_id => blog.id)
				= link_to "删除", delete_blog_tools_path(:blog_id => blog.id)
.pagination= will_paginate @blogs

app/views/tools/list_comments.html.haml
%table#list_comments
	.head1 留言列表
	%tr
		%td 访问者
		%td 日期
		%td 内容
		%td 博客原文
		%td 操作
	- @comments.each do |comment|
		%tr
			%td= comment.visitor.display_name
			%td= comment.time_str
			%td= comment.content
			%td= link_to "博客原文", blog_path(comment.blog)
			%td= link_to "删除", delete_comment_tools_path(:comment_id => comment.id)
.pagination= will_paginate @comments

app/views/tools/list_visitors.html.haml
%table#list_blogs
	.head1 访问者列表
	#update_location= link_to "更新地址", update_ip_location_tools_path
	%tr
		%td 昵称
		%td IP
		%td 地址
		%td 访问次数
		%td 最后访问
	- @visitors.each do |visitor|
		%tr
			%td= visitor.name
			%td= visitor.ip
			%td= visitor.location
			%td= visitor.count
			%td= visitor.last_access
.pagination= will_paginate @visitors

app/views/tools/new_blog.html.haml
.head1 新建博客
#new_blog
	.trans_add= link_to "添加链接", "#", :id => "link_add"
	.trans_add= link_to "添加代码", "#", :id => "code_add"
	= form_for @blog, :url => create_blog_tools_path, :html => {:multipart => true} do |f|
		.image_upload
			上传图片
			= f.file_field :image
		.music_upload
			上传音乐
			= f.file_field :music
		.attachment_upload
			上传附件
			= f.file_field :attach
		= f.submit "upload"
		= f.text_field :title, :class => "title_input"
		= f.text_area :text, :class => "text_input"
		= f.select :blog_type_id, types_option
		= f.submit "发表", :class => "confirm_button"
		

app/views/tools/new_blog_type.html.haml
.head1 新建分类
#new_blog_type
	= form_for @blog_type, :url => create_blog_type_tools_path do |f|
		= f.text_field :name, :class => "title_input"
		= f.text_area :desc, :class => "text_input"
		= f.submit "创建", :class => "confirm_button"
		