config/routes.rb
GBlog::Application.routes.draw do

  
  resources :blogs
  
  resources :blog_types

  resources :comments
  
  resources :tools do 
    collection do 
      get "new_blog"
      post "create_blog"
      get "list_blogs"
      get "edit_blog"
      put "update_blog"
      get "delete_blog"
      get "new_blog_type"
      post "create_blog_type"
      get "list_blog_types"
      get "edit_blog_type"
      put "update_blog_type"
      get "delete_blog_type"
      get "list_comments"
      get "delete_comment"
      get "list_visitors"
      get "update_ip_location"
    end
  end
  
  resources :admins do
    collection do 
      get "admin_show"
      get "admin_edit"
      put "admin_update"
    end
  end
  
  resources :statuses

  root :to => "blogs#home"

end

app/views/admins/admin_edit.html.haml
.head1 
	- if @type == "info"
		= "修改资料"
	- elsif @type == "avatar"
		= "修改头像"
	- elsif @type == "photo"
		= "修改照片"
	- elsif @type == "desc"
		= "修改简介"
#admin_edit
	= form_for @admin, :url => admin_update_admins_path, :html => {:multipart => (@type == "avatar" || @type == "photo")} do |f|
		- if @type == "info"
			%table
				%tr
					%td 昵称
					%td= f.text_field :nick_name
				%tr
					%td 真名
					%td= f.text_field :true_name
				%tr
					%td 生日
					%td= f.text_field :birthday
				%tr
					%td 公司
					%td= f.text_area :company, :class => "info_edit"
				%tr
					%td 职位
					%td= f.text_field :title
				%tr
					%td QQ
					%td= f.text_field :qq
				%tr
					%td 新浪微博
					%td= f.text_area :weibo, :class => "info_edit"
				%tr
					%td 微信号
					%td= f.text_field :wechat
				%tr
					%td 邮箱
					%td= f.text_field :mail
		- elsif @type == "avatar"
			= f.file_field :avatar
		- elsif @type == "photo"
			= f.file_field :photo
		- elsif @type == "desc"
			= f.text_area :desc, :class => "text_input desc_edit"
		= submit_tag

app/views/admins/admin_show.html.haml
#about_me
	.map
		%span.var= @admin.nick_name
		%span.oth = {
	.sub_info
		%span.cla string
		%span.var name
		%span.oth =
		%span.str= "\"#{@admin.true_name}\""
		%span.oth , 
	.sub_info
		%span.cla date
		%span.var birthday
		%span.oth =
		%span.obj= @admin.birthday
		%span.oth ,
	.sub_info
		%span.cla location
		%span.var company
		%span.oth =
		%span.str= "\"#{@admin.company}\""
		%span.oth ,
	.sub_info
		%span.cla string
		%span.var title
		%span.oth =
		%span.str= "\"#{@admin.title}\""
		%span.oth ,
	.sub_info
		%span.cla long int
		%span.var qq
		%span.oth =
		%span.var= @admin.qq
		%span.oth ,
	.sub_info
		%span.cla link
		%span.var sina_weibo
		%span.oth =
		%span= link_to "@邱晗_goshan", @admin.weibo, :target => "blank"
		%span.oth ,
	.sub_info
		%span.cla string
		%span.var wechat
		%span.oth =
		%span.str= "\"#{@admin.wechat}\""
		%span.oth ,
	.sub_info
		%span.cla string
		%span.var mail
		%span.oth =
		%span.str= "\"#{@admin.mail}\""
	.map 
		%span.oth }
	.comment
		= "/********************************************************************************************"
		%pre= @admin.print_desc
		= "/********************************************************************************************"
	#about_me_photo= image_tag @admin.photo.url
		