config/routes.rb
GBlog::Application.routes.draw do

  
  resources :blogs
  
  resources :blog_types

  resources :comments
  
  resources :tools do 
    collection do 
      get "new_blog"
      post "create_blog"
      get "list_blogs"
      get "edit_blog"
      put "update_blog"
      get "delete_blog"
      get "new_blog_type"
      post "create_blog_type"
      get "list_blog_types"
      get "edit_blog_type"
      put "update_blog_type"
      get "delete_blog_type"
      get "list_comments"
      get "delete_comment"
      get "list_visitors"
      get "update_ip_location"
    end
  end
  
  resources :admins do
    collection do 
      get "admin_show"
      get "admin_edit"
      put "admin_update"
    end
  end
  
  resources :statuses

  root :to => "blogs#home"

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  
  before_filter :auth
  
  layout "tools"
  
  def index
    page = params[:page] || 1
    @statuses = Status.order("created_at asc").paginate(:page => page, :per_page => 20)
  end
  
  def new
    @status = Status.new
  end
  
  def create
    Status.create!(params[:status])
    
    redirect_to root_path
  end
  
  def edit
    @status = Status.find_by_id(params[:id])
  end
  
  def update
    @status = Status.find_by_id(params[:id])
    @status.update_attributes!(params[:status])
    
    redirect_to root_path
  end
  
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/edit.html.haml
.head1 修改状态
#edit_status
	= form_for @status do |f|
		= f.text_area :content, :class => "text_input"
		= f.submit

app/views/statuses/index.html.haml
.head1 历史状态
%table#statuses_feed
	- @statuses.each do |status|
		%tr
			%td.status_content= status.content
			%td= status.created_at.to_date
			%td= link_to "修改", edit_status_path(status)
.pagination= will_paginate @statuses

app/views/statuses/new.html.haml
.head1 编辑状态
#new_status
	= form_for @status do |f|
		= f.text_area :content, :class => "text_input"
		= f.submit