config/routes.rb
GBlog::Application.routes.draw do

  
  resources :blogs
  
  resources :blog_types

  resources :comments
  
  resources :tools do 
    collection do 
      get "new_blog"
      post "create_blog"
      get "list_blogs"
      get "edit_blog"
      put "update_blog"
      get "delete_blog"
      get "new_blog_type"
      post "create_blog_type"
      get "list_blog_types"
      get "edit_blog_type"
      put "update_blog_type"
      get "delete_blog_type"
      get "list_comments"
      get "delete_comment"
      get "list_visitors"
      get "update_ip_location"
    end
  end
  
  resources :admins do
    collection do 
      get "admin_show"
      get "admin_edit"
      put "admin_update"
    end
  end
  
  resources :statuses

  root :to => "blogs#home"

end

app/views/layouts/application.html.erb
<%admin = admin_info%>

<!DOCTYPE html>
<html>
<head>
  <title>goshan Blogs</title>
  <%= stylesheet_link_tag "/stylesheets/highlight/sunburst.css"%>
  <%= javascript_include_tag "/javascripts/highlight.pack.js"%>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="nav_bar">
		<%= image_link "/assets/logo.png", root_path, :id => "logo"%>
		<div id="heading">
			<div id="slogen">:FallenCoder => "goshan"</div>
			<div id="status"><%= admin.status%></div>
		</div>
	</div>
	<div id="side_bar">
		<%= image_tag admin.avatar.url, :id => "avatar"%>
		<div id="nick_name"><%= admin.nick_name%></div>
		<div id="info"><%= admin.company%></div>
		<div id="about_me_link"><%= link_to "<关于我>", admin_show_admins_path%></div>
		<div id="hot_types">
			<div id="hot_types_head">
				热门分类
				<%= link_to ">>", blog_types_path, :id => "show_types"%>
			</div>
			<%hot_types.each do |type| %>
				<div class="type_item">
					<%= link_to type.name, blogs_path(:blog_type_id => type.id), :class => "item_name"%>
					<span class ="blogs_count"><%= type.blogs_count%></span>
				</div>
			<%end%>
		</div>
	</div>
	<div id="content">
		<%= yield %>
	</div>
</body>
</html>

app/views/layouts/no_side.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>about ME</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="nav_bar">
		<%= image_link "/assets/logo.png", root_path, :id => "logo"%>
		<div id="heading">
			<div id="slogen">:FallenCoder => "goshan"</div>
			<div id="status"><%= admin_info.status%></div>
		</div>
	</div>
	<div id="info_content">
		<%= yield %>
	</div>
</body>
</html>

app/views/layouts/tools.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>goshan Blogs tools</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="tools_content">
		<%= yield %>
	</div>
</body>
</html>